### PR TITLE
Re-added byebug, made it require: false, removed from spec_helper.

### PR DESCRIPTION
**Pull request by mauro-oto**
Hey @etagwerker, @schmierkov, 

This PR adds `byebug` back in, makes it `require: false`, and removes it from `spec_helper`, you'll need to require it to use it. 

Please check it out, thanks!

### CODE REVIEW

**Comment by schmierkov** [comment]
@mauro-oto seems not to work, still receiving an error on bundling
```
Gem::InstallError: byebug requires Ruby version >= 2.0.0.
```
checkout https://travis-ci.org/ombulabs/freckler/jobs/105780839

**Comment by schmierkov** [comment]
@mauro-oto works now! cheers! 🍸

**Comment by mauro-oto** [comment]
Thanks!!!

**Comment by etagwerker** [comment]
@mauro-oto @schmierkov Great, thanks!

**Pull request merged**
